### PR TITLE
Bowerized things

### LINKED ISSUE #1: Remove vendor/ember-starter-kit/ and vendor/handlebars.js in favor of versions from bower
handlerbars 1.0.0 is required for emblem

Additionally the ember versions from bower are out of date (rc6 instead of rc6.1).  So we currently use a manually downloaded handlebars.js (1.0.0) as well as the current release of the ember-starter-kit for ember and jquery.

When the bower versions of all these packages are recent enough, switch to the bower versions and remove the manually managed dependencies.

### PR DESCRIPTION
**Pull request by dbashford**
Fixes #1

Spiffed up the bowering in prep for coming 1.0 release which includes bower by default.

### CODE REVIEW

**Comment by dbashford** [comment]
I added a commit pointing to the new site and fixing the README.  `npm install mimosajs` won't do anything. =)

Let me know if you have any trouble with this PR!

**Comment by breathe** [comment]
Thanks Dave!  Sorry for the delayed merge -- my work tends to put me places without internet access for very long periods of time ...

**Comment by dbashford** [comment]
No problem!

I'll have another PR coming tomorrow morning (EST) after I push `1.0.0`.  

The `handlebars` and `emblem` `lib` settings have been moved to a `compilers.lib` which allows for all compilers to be provided via the config.

**Comment by breathe** [comment]
Awesome!  I saw that change was coming but wasn't sure in which mimosa version it was going to land.  

I'm back in the land of internet (albeit slow internet) so I'll happily merge and upgrade my other projects to 1.0.0 when it lands.  Many Thanks!

**Comment by dbashford** [comment]
All that stuff has been sitting in the RC1 branch as I've been working on it.  Too many big changes to try and do them in master and keep master updated for various fixes.

**Pull request merged**
