### PR TITLE
various adjustments to get app/tests running

### PR DESCRIPTION
**Pull request by dbashford**
1. Forcing mimosa version `0.14.5`
2. upgrading `vendor/handlebars` to `1.0.0`
3. pointing testrunner at `vendor/handlebars`

### CODE REVIEW

**Comment by breathe** [comment]
I see you changed app/test/testrunner.html -- with the change I made to testem.json -- I don't think that file actually gets referenced at all.  I intended to remove the ./test directory ...

Think the testrunner.html that needs editing is at assets/testrunner.html ...?

**Comment by dbashford** [comment]
Sorry, your `testem.json` was still pointed at `test/testrunner` so I went with that.  I also hadn't merged from the work you had done previously so I didn't see the other test runner.

Switching to that one also made me update all the paths to include the `test` prefix you put in the `testem.json`.

But I think it all looks good now.

**Comment by dbashford** [comment]
If there are any other tweaks to make, it'll have to wait til tomorrow.  Is getting late. =)

Thanks for letting me work through this with ya!

**Comment by breathe** [comment]
No, many thanks to you for the expert help, I'm sorry to have this broken.

But I think that the testrunner at ./test/testrunner.html is not needed -- at least according to my understanding ... 

The two config items in testem.json  have the effect of pointing testem clients at (assuming testem is run on port 7567 -- can't remember the default port)

http://localhost:7567/test/testrunner.html

Which the testem route rule interprets as a request for the resource at

./public/testrunner.html

Then any subsequent relative requests for resources (./javascripts/app/app.js and ./img/foo.jpeg) look like this in the browser context

http://localhost:7567/test/img/food.jpeg 
http://localhost:7567/test/javascripts/app/app.js

also getting correctly resolved to files at

./public/img/food.jpeg
./public/app/app.js

Does this sound right and match the behavior you see ...?

Maybe it's wrong of me to want to be able to reuse the same URL structure of my app in the tests ... ?  But this seemed like a nice goal to me ...

**Comment by breathe** [comment]
On further reflection I think that all the relative urls will work correctly if in testem.json

test_page is set to ./public/testrunner.html -- relative urls for any application resources will resolve correctly -- it's only absolute urls which would be different from the URL context of the normal application .. 

Testem doesn't provide any way to change the filesystem contex for absolute -- it's always the directory containing the testem.jsom -- but I think the above approach is doing what I wanted it to do -/ at lest for this application ...

Sorry for any confusion I may have caused -- hopefully you agree that it at makes sense what I was trying to do ...

**Comment by dbashford** [comment]
I'm fine with you trying to get the URLs all sane and good.  I didn't tinker with it much.

Not sure when I'd get a chance to play more with this.  Do you think it might be worth merging the PR just to get things working and then doubling back to tidy up the URLs?  That way at least the app is working if people try it out.

**Comment by breathe** [comment]
Ok fair enough.  Thanks for the pr!

**Pull request merged**
